name: Main
on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # allows manual run
  workflow_dispatch:

  # run on every push on the main branch
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Default metrics (with private contributions)
        uses: lowlighter/metrics@latest
        with:
          filename: output/metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }} # ← Classic token に変更！
          base: header, activity, community, repositories, metadata
          plugin_activity: yes
          plugin_activity_visibility: all  # ← private contributionsを含める

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: output/details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories_skipped: chatbot-ui, gitHub-readme-stats-clone, PL0-compiler
          plugin_languages: yes
          plugin_languages_ignored: tex, less, qmake, lex, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_activity_visibility: all  # ←これも追加

      - name: Compact achievements (private aware)
        uses: lowlighter/metrics@latest
        with:
          filename: output/metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer,
            developer, scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_activity_visibility: all
